In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

C:\Users\TJ\anaconda3\envs\ml01-02\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [4]:
items

['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [5]:
# LabelEncoder 객체 생성
encoder = LabelEncoder()
# fit : 식에 맞는 값을 찾기 -> 유니크처리, 정렬 -> 인덱스 찾기
encoder.fit(items)
# 변환: transform
labels = encoder.transform(items)
labels


array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [6]:
# 유니크, 정렬 처리한 결과 확인
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [16]:
# 숫자로 인코딩 => 문자열 변환
encoder.inverse_transform([3,3,3,3])

array(['선풍기', '선풍기', '선풍기', '선풍기'], dtype='<U4')

### One Hot Encoding

In [17]:
# LabelEncoder 객체 생성
encoder = LabelEncoder()
# fit : 식에 맞는 값을 찾기 -> 유니크처리, 정렬 -> 인덱스 찾기
encoder.fit(items)
# 변환: transform
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [19]:
from sklearn.preprocessing import OneHotEncoder

items

['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [27]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
#2차원 데이터로 변환
labels = labels.reshape(-1,1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]], dtype=int64)

In [24]:
# One Hot Encoding 적용
oh_encoder = OneHotEncoder()
# labels를 2차원으로 변경 할수 앖에 없음.
oh_encoder.fit(labels) # 식만 생성된 것 (변환 x)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [37]:
# DataFrame 편하게 원-핫 인코딩 처리 메소드 : get_dummies()
df = pd.DataFrame(
      {'items' : ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']}
)
df

items
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [38]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0         1          0         0          0           0          0
1         0          1         0          0           0          0
2         0          0         0          0           1          0
3         0          0         0          0           0          1
4         0          0         0          1           0          0
5         0          0         0          1           0          0
6         0          0         1          0           0          0
7         0          0         1          0           0          0

In [40]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터셋을 로딩하고 DataFrame 으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [42]:
# 평균, 분산 값 구하기
print(iris_df.mean()) # 평균(컬럼기준)  **kwargs --> key;value 값 dictionary
                      #                  *kwargs --> 가변인자
print(iris_df.var()) # 분산

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [58]:
# StandardScaler
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()
scaler.fit(iris_df) # 변환에 필요한 값을 구해야 한다.
                    # 평균, 표준편차
# 변환
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.mean(),"\nfeature들의 평균 값")
print(iris_df_scaled.var(), "\nfeature들의 분산 값")

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64 
feature들의 평균 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64 
feature들의 분산 값


In [59]:
iris_df_scaled

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

#### MinMaxScaler

In [61]:
# MinMaxScaler : 변량을 0~1 값으로 변환
from sklearn.preprocessing import MinMaxScaler

# 객체 생성
scaler = MinMaxScaler()

# min, max value 구해야 한다. -> fit()
scaler.fit(iris_df)


MinMaxScaler()

In [63]:
# 변환
iris_scaled = scaler.transform(iris_df)
type(iris_scaled)

numpy.ndarray

In [64]:
iris_df_scaled = pd.DataFrame(
      data = iris_scaled
    , columns = iris.feature_names
)
iris_df_scaled.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

In [66]:
iris_df_scaled.min() # 컬럼별 최소값
iris_df_scaled.max() # 컬럼별 최대값

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64